services:
  # Postgres
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=arxarx
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
  # mongoDb
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=arvis
      - MONGO_INITDB_ROOT_PASSWORD=arxarx
    ports:
      - 27017:27017
    volumes:
      - /var/lin/mongodb/data
  # RabbitMq
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
  # AuctionService
  auction-service:
    image: arvisiljins/auction-service:latest
    build:
      context: .
      dockerfile: src/AuctionService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_URLS=http://+:7777
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=arxarx;Database=auctions
      - IdentityServiceUrl=http://identity-service
      - Kestrel__Endpoints__Grpc__Protocols=Http2
      - Kestrel__Endpoints__Grpc__Url=http://+:7777
      - Kestrel__Endpoints__WebApi__Protocols=Http1
      - Kestrel__Endpoints__WebApi__Url=Http://+:80
    ports:
      - 7001:80
      - 7777:7777
    depends_on:
      - postgres
      - rabbitmq
  # SearchService
  search-service:
    image: arvisiljins/search-service:latest
    build:
      context: .
      dockerfile: src/SearchService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__MongoDbConnection=mongodb://arvis:arxarx@mongodb
      - AuctionServiceUrl=http://auction-service
    ports:
      - 7002:80
    depends_on:
      - mongodb
      - rabbitmq
  # BiddsService
  biding-service:
    image: arvisiljins/biding-service:latest
    build:
      context: .
      dockerfile: src/BiddingService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__BidsConnection=mongodb://arvis:arxarx@mongodb
      - IdentityServiceUrl=http://identity-service
      - GrpcAuction=http://auction-service:7777
    ports:
      - 7003:80
    depends_on:
      - mongodb
      - rabbitmq
  # IdentityService
  identity-service:
    image: arvisiljins/identity-service:latest
    build:
      context: .
      dockerfile: src/IdentityService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=arxarx;Database=identitys
    ports:
      - 5001:80
    depends_on:
      - postgres
  # GatewayService
  gateway-service:
    image: arvisiljins/gateway-service:latest
    build:
      context: .
      dockerfile: src/GatewayService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
    ports:
      - 6001:80
  # NotificationService
  notification-service:
    image: arvisiljins/notification-service:latest
    build:
      context: .
      dockerfile: src/NotificationService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
    ports:
      - 7004:80
    depends_on:
      - rabbitmq
