services:
  # Postgres
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=arxarx
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
  # mongoDb
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=arvis
      - MONGO_INITDB_ROOT_PASSWORD=arxarx
    ports:
      - 27017:27017
    volumes:
      - /var/lin/mongodb/data
  # RabbitMq
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
  # AuctionService
  auction-service:
    image: arvisiljins/auction-service:latest
    build:
      context: .
      dockerfile: src/AuctionService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=arxarx;Database=auctions
      - IdentityServiceUrl=http://identity-service
    ports:
      - 7001:80
    depends_on:
      - postgres
      - rabbitmq
  # SearchService
  search-service:
    image: arvisiljins/search-service:latest
    build:
      context: .
      dockerfile: src/SearchService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__MongoDbConnection=mongodb://arvis:arxarx@mongodb
      - AuctionServiceUrl=http://auction-service
    ports:
      - 7002:80
    depends_on:
      - postgres
      - rabbitmq
  # IdentityService
  identity-service:
    image: arvisiljins/identity-service:latest
    build:
      context: .
      dockerfile: src/IdentityService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=arxarx;Database=identitys
    ports:
      - 5001:80
    depends_on:
      - postgres
  # GatewayService
  gateway-service:
    image: arvisiljins/gateway-service:latest
    build:
      context: .
      dockerfile: src/GatewayService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
    ports:
      - 6001:80
