networks:
  custom:
    ipam:
      config:
        - subnet: 10.5.0.0/16
services:
  # Postgres
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=arxarx
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
    networks:
      custom:
  # mongoDb
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=arvis
      - MONGO_INITDB_ROOT_PASSWORD=arxarx
    ports:
      - 27017:27017
    volumes:
      - /var/lin/mongodb/data
    networks:
      custom:
  # RabbitMq
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      custom:
  # AuctionService
  auction-service:
    image: arvisiljins/auction-service:latest
    build:
      context: .
      dockerfile: src/AuctionService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_URLS=http://+:7777
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=arxarx;Database=auctions
      - IdentityServiceUrl=http://identity-service
      - Kestrel__Endpoints__Grpc__Protocols=Http2
      - Kestrel__Endpoints__Grpc__Url=http://+:7777
      - Kestrel__Endpoints__WebApi__Protocols=Http1
      - Kestrel__Endpoints__WebApi__Url=Http://+:80
    ports:
      - 7001:80
      - 7777:7777
    depends_on:
      - postgres
      - rabbitmq
    networks:
      custom:
  # SearchService
  search-service:
    image: arvisiljins/search-service:latest
    build:
      context: .
      dockerfile: src/SearchService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__MongoDbConnection=mongodb://arvis:arxarx@mongodb
      - AuctionServiceUrl=http://auction-service
    ports:
      - 7002:80
    depends_on:
      - mongodb
      - rabbitmq
    networks:
      custom:
  # BiddsService
  biding-service:
    image: arvisiljins/biding-service:latest
    build:
      context: .
      dockerfile: src/BiddingService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__BidsConnection=mongodb://arvis:arxarx@mongodb
      - IdentityServiceUrl=http://identity-service
      - GrpcAuction=http://auction-service:7777
    ports:
      - 7003:80
    depends_on:
      - mongodb
      - rabbitmq
    networks:
      custom:
  # IdentityService
  identity-service:
    image: arvisiljins/identity-service:latest
    build:
      context: .
      dockerfile: src/IdentityService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - ClientApp=app.auctions-house.com
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=arxarx;Database=identitys
      - VIRTUAL_HOST=id.auctions-house.com
    depends_on:
      - postgres
    networks:
      custom:
        ipv4_address: 10.5.0.200
  # GatewayService
  gateway-service:
    image: arvisiljins/gateway-service:latest
    build:
      context: .
      dockerfile: src/GatewayService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - ClientApp=http://app.auctions-house.com
      - VIRTUAL_HOST=api.auctions-house.com
    networks:
      custom:
  # NotificationService
  notification-service:
    image: arvisiljins/notification-service:latest
    build:
      context: .
      dockerfile: src/NotificationService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
    ports:
      - 7004:80
    depends_on:
      - rabbitmq
    networks:
      custom:
  # Web app
  web-app:
    image: arvisiljins/web-app:latest
    build:
      context: .
      dockerfile: frontend/Dockerfile
    volumes:
      - /var/lib/web/data
    extra_hosts:
      - id.auctions-house.com:10.5.0.200
    environment:
      - NEXTAUTH_SECRET=somthingreallysecreat
      - NEXTAUTH_URL=http://app.auctions-house.com
      - NEXTAUTH_URL_INTERNAL=http://web-app:3000
      - API_URL=http://gateway-service/
      - API_ISSUER=http://id.auctions-house.com
      - NEXT_PUBLIC_API_NOTIFICATIONS=http://gateway-service/notifications
      - VIRTUAL_HOST=app.auctions-house.com
      - VIRTUAL_PORT=3000
    networks:
      custom:
  # nginx
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - 80:80
      - 443:443
    networks:
      custom:
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./devcerts:/etc/nginx/certs
