apiVersion: apps/v1
kind: Deployment
metadata:
  name: auction-service
spec:
  selector:
    matchLabels:
      app: auction-service
  template:
    metadata:
      labels:
        app: auction-service
    spec:
      containers:
      - name: auction-service
        image: arvisiljins/auction-service
        imagePullPolicy: Never
        env:
          - name: RabbitMq__Host
            value: rabbit-clusterip
          - name: RabbitMq__Username
            value: arvis
          - name: RabbitMq__Password
            value: arxarx123
          - name: ConnectionStrings__DefaultConnection
            value: Server=postgres-clusterip:5432;User Id=postgres;Password=arxarx;Database=auctions 
          - name: IdentityServiceUrl
            value: https://id.auction-house.shop
          - name: Kestrel__Endpoints__Grpc__Protocols
            value: Http2      
          - name: Kestrel__Endpoints__Grpc__Url
            value: http://+:7777
          - name: Kestrel__Endpoints__WebApi__Protocols
            value: Http1     
          - name: Kestrel__Endpoints__WebApi__Url
            value: Http://+:80
---
apiVersion: v1
kind: Service
metadata:
  name: auction-clusterip
spec:
  selector:
    app: auction-service
  ports:
  - port: 80
    targetPort: 80
    name: web
  - port: 7777
    targetPort: 7777
    name: grpc
  

   


