apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        image: arvisiljins/web-app
        imagePullPolicy: Never
        env:
          - name: NEXTAUTH_SECRET
            value: somthingreallysecreat
          - name: NEXTAUTH_URL
            value: https://app.auctions-house.com
          - name: NEXTAUTH_URL_INTERNAL
            value: http://web-app:3000
          - name: API_URL
            value: http://gateway-clusterip/
          - name: API_ISSUER
            value: https://id.auctions-house.shop
        ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-clusterip
spec:
  type: ClusterIP
  selector:
    app: web-app
  ports:
  - port: 80
    targetPort: 80
    name: web
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-lb
spec:
  type: LoadBalancer
  selector:
    app: webapp
  ports:
  - port: 3000
    targetPort: 3000



